services:
  database:
    container_name: pit2-database
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    container_name: pit2-backend
    build:
      context: ./backend
      tags:
        - "allan-nubling/pit2-backend"
    depends_on:
      - database
    environment:
      DB_HOST: pit2-database
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "3000:3000"
